// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHluIXKG-aZFm1m1_nGKR8F4uHrYASkg',
    appId: '1:610905379965:web:d044f883e3adf0f4b9cd14',
    messagingSenderId: '610905379965',
    projectId: 'foggi-e9109',
    authDomain: 'foggi-e9109.firebaseapp.com',
    storageBucket: 'foggi-e9109.firebasestorage.app',
    measurementId: 'G-3YER6VQMBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrtug7oH2M-BiQg4L1Q-2835bEIwKYedM',
    appId: '1:610905379965:android:cf3b287467684071b9cd14',
    messagingSenderId: '610905379965',
    projectId: 'foggi-e9109',
    storageBucket: 'foggi-e9109.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOWkk1Hv6-Nr8DGTgUp1jnNZslG_KbaA',
    appId: '1:610905379965:ios:a2e964fc92723d0db9cd14',
    messagingSenderId: '610905379965',
    projectId: 'foggi-e9109',
    storageBucket: 'foggi-e9109.firebasestorage.app',
    iosClientId: '610905379965-c8kup774uu1325f1am87lve7lv1umvb0.apps.googleusercontent.com',
    iosBundleId: 'com.foggi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOWkk1Hv6-Nr8DGTgUp1jnNZslG_KbaA',
    appId: '1:610905379965:ios:a2e964fc92723d0db9cd14',
    messagingSenderId: '610905379965',
    projectId: 'foggi-e9109',
    storageBucket: 'foggi-e9109.firebasestorage.app',
    iosClientId: '610905379965-c8kup774uu1325f1am87lve7lv1umvb0.apps.googleusercontent.com',
    iosBundleId: 'com.foggi.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHluIXKG-aZFm1m1_nGKR8F4uHrYASkg',
    appId: '1:610905379965:web:0d9df83034509863b9cd14',
    messagingSenderId: '610905379965',
    projectId: 'foggi-e9109',
    authDomain: 'foggi-e9109.firebaseapp.com',
    storageBucket: 'foggi-e9109.firebasestorage.app',
    measurementId: 'G-BESLRBLKQT',
  );
}
